module.exports = {
  "USANCA": "AMC Anchorage AK",
  "USAUZA": "Aurora Bpost",
  "USCHIA": "AMC O'hare IL",
  "USEWRA": "AMC Newark NJ",
  "USEWRY": "AMC Newark NJ",
  "USSEAA": "AMC Seattle WA",
  "USSEAE": "AMC Seattle",
  "USSEAF": "AMC Seattle",
  "USSEAI": "AMC Seattle WA",
  "USSEAK": "AMC Seattle WA",
  "USSEAS": "AMC Seattle WA",
  "USSEAY": "AMC Seattle WA",
  "USCHID": "Chicago D LA Poste FR",
  "USCHIE": "Chicago E",
  "USCHIP": "Chicago",
  "USCHIS": "Chicago S",
  "USNYCA": "Church ST NEW York",
  "USORDL": "Chicago GM Etoe",
  "USUAKA": "Carlstadt, Mauritius Post LTD",
  "USDESZ": "DES Plaines IL Etoe",
  "USELPA": "EL Paso TX",
  "USELPY": "EL Paso TX",
  "USFMJV": "Farmingdale",
  "USJECA": "Foreign Center Jersey City NJ",
  "USJECC": "Foreign Center Jersey City NJ",
  "USJECD": "Foreign Center Jersey City NJ",
  "USJECE": "Foreign Center Jersey City NJ",
  "USJECF": "Foreign Center Jersey City NJ",
  "USJECG": "Foreign Center Jersey City NJ",
  "USJECI": "Foreign Center Jersey City NJ",
  "USJECK": "Foreign Center Jersey City NJ",
  "USJECM": "Foreign Center Jersey City NJ",
  "USJECS": "Foreign Center Jersey City NJ",
  "USJECT": "Foreign Center Jersey City NJ",
  "USJECY": "Foreign Center Jersey City NJ",
  "USNYCB": "FDR Station NY",
  "USUJDZ": "Folcroft PI Etoe",
  "USHLUZ": "Hollis NY Etoe",
  "USHNLY": "ISC HNL Honolulu",
  "USJFKA": "ISC NEW York NY",
  "USJFKC": "ISC NEW York NY",
  "USJFKD": "ISC NEW York NY",
  "USJFKE": "ISC NEW York NY",
  "USJFKF": "ISC NEW York NY",
  "USJFKG": "ISC NEW York NY",
  "USJFKH": "ISC NEW York NY",
  "USJFKI": "ISC NEW York NY",
  "USJFKK": "ISC NEW York NY",
  "USJFKM": "ISC NEW York NY",
  "USJFKY": "ISC JFK NEW York",
  "USLAXA": "ISC LOS Angeles CA",
  "USLAXE": "ISC LOS Angeles CA",
  "USLAXF": "ISC LOS Angeles CA",
  "USLAXI": "ISC LOS Angeles CA",
  "USLAXK": "ISC LOS Angeles CA",
  "USLAXY": "ISC LAX LOS Angeles CA",
  "USMIAA": "ISC Miami FL",
  "USMIAE": "ISC Miami FL",
  "USMIAF": "ISC Miami FL",
  "USMIAI": "ISC Miami FL",
  "USMIAK": "ISC Miami FL",
  "USMIAS": "ISC Miami FL",
  "USMIAY": "ISC MIA Miami FL",
  "USOAKA": "ISF Oakland CA A",
  "USOAKK": "ISF Oakland CA",
  "USOAKS": "ISF Oakland CA",
  "USOAKY": "ISF Oakland CA",
  "USORDA": "ISC Chicago IL",
  "USORDB": "ISC Chicago IL",
  "USORDE": "ISC Chicago IL",
  "USORDF": "ISC Chicago IL",
  "USORDG": "ISC Chicago IL",
  "USORDI": "ISC Chicago IL",
  "USORDK": "ISC Chicago IL",
  "USORDS": "ISC Chicago IL S",
  "USORDY": "ISC ORD Chicago IL",
  "USSFOA": "ISC SAN Francisco",
  "USSFOE": "ISC SAN Francisco",
  "USSFOF": "ISC SAN Francisco",
  "USSFOG": "ISC SAN Francisco CA",
  "USSFOH": "ISC SAN Francisco",
  "USSFOI": "ISC SAN Francisco",
  "USSFOK": "ISC SAN Francisco",
  "USSFOY": "ISC SFO SAN Francisco",
  "USJFKL": "J F Kennedy APT",
  "USJRIA": "Jericho NEW York",
  "USNYCD": "JA Farley NY",
  "USXHEM": "Kearny Mtesc NJ",
  "USLAXC": "LAX LOS Angeles",
  "USLAXD": "LOS Angeles LA Poste FR",
  "USLAXL": "LOS Angeles GM Etoe",
  "USLAXS": "LOS Angeles S",
  "USLGAA": "LA Guardia Airport NY",
  "USLGAY": "LA Guardia Airport NY",
  "USMIAC": "Miami DP",
  "USMIAD": "Miami D",
  "USMIAG": "Miami USA",
  "USNYCC": "Morgan Station NY",
  "USNYCS": "Morgan Station NY",
  "USNYCY": "Morgan Station NY",
  "USONRA": "Monroe NEW Jersey LA Poste FR",
  "USDFWA": "North Texas, Dallas, P&dc",
  "USEWRB": "Newark",
  "USEWRD": "Newark GM Etoe",
  "USJECU": "NEW Jersey U Emirates Post",
  "USNYCK": "NEW York NY",
  "USHNLA": "P&dc Honolulu HI",
  "USHNLB": "P&dc Honolulu HI",
  "USHNLK": "P&dc Honolulu HI",
  "USHNLS": "P&dc Honolulu HI",
  "USPHLF": "Philadelphia LA Poste (fr)",
  "USSANA": "P&dc SAN Diego CA",
  "USRBDZ": "Redondo Beach, CA Etoe",
  "USSFOS": "SAN Francisco S",
  "USSGVA": "Sterling Bpost",
  "USUYKA": "Secaucus Bpost"
}
